In [1]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [22]:
a = np.array([i for i in range(1,11)], dtype=float)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [28]:
a = np.zeros((3, 3), dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [31]:
result_array = []
for _ in range(5):
    result_array.append(np.random.randint(1, 10, 5))

a = np.array(result_array, dtype=float)
a

array([[7., 9., 7., 9., 7.],
       [9., 4., 1., 8., 8.],
       [3., 9., 5., 7., 3.],
       [9., 1., 9., 7., 7.],
       [4., 7., 8., 7., 1.]])

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [18]:
result_array = []
for _ in range(4):
    result_array.append(np.random.random(4))
    
a = np.array(result_array, dtype=float)
a

array([[0.65747449, 0.36821015, 0.00320404, 0.52557623],
       [0.09601667, 0.93455856, 0.63924585, 0.75347186],
       [0.21059049, 0.61382081, 0.02459921, 0.67521198],
       [0.55455279, 0.4141005 , 0.12707749, 0.67168269]])

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [23]:
arr_1 = np.random.randint(1, 10, 5)
arr_2 = np.random.randint(1, 10, 5)

arr_1 + arr_2, arr_1 - arr_2, arr_1 * arr_2,  

(array([ 5, 13,  9,  5,  8]),
 array([-1, -5,  3,  3,  0]),
 array([ 6, 36, 18,  4, 16]))

6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [55]:
arr_1 = np.random.randint(1, 10, 7)
arr_2 = np.random.randint(1, 10, 7)

np.dot(arr_1, arr_2)

157

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [15]:
result_array = []
for _ in range(2):
    result_array.append([j for j in np.random.randint(1, 10, 2)])
m1 = np.array(result_array, dtype=int)    
    
result_array = []
for _ in range(2):
    result_array.append([j for j in np.random.randint(1, 10, 3)])
m2 = np.array(result_array, dtype=int)      
 
m3 = np.dot(m1, m2)
m3

array([[40, 38, 22],
       [12, 25,  9]])

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [18]:
result_array = []
for _ in range(3):
    result_array.append([j for j in np.random.randint(1, 10, 3)])
m1 = np.array(result_array, dtype=int)

m1_inv = np.linalg.inv(m1)

m1_inv

array([[ 5.76923077e-01, -6.79487179e-01,  5.00000000e-01],
       [ 1.53846154e-01, -2.56410256e-02, -1.81014624e-18],
       [-8.07692308e-01,  8.84615385e-01, -5.00000000e-01]])

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [30]:
result_array = []
for _ in range(4):
    result_array.append([j for j in np.random.random(4)])
m1 = np.array(result_array, dtype=float)

m1.T

array([[0.67009986, 0.4782241 , 0.53793906, 0.67171471],
       [0.27329185, 0.38685186, 0.11987227, 0.98337366],
       [0.85442729, 0.51381589, 0.07794182, 0.55026003],
       [0.52008294, 0.19520021, 0.29023774, 0.6496281 ]])

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [33]:
result_array = []
for _ in range(3):
    result_array.append(np.array(np.random.randint(1, 10, 4), dtype=float))
m1 = np.array(result_array, dtype=float)

v1 = np.array(np.random.randint(1, 10, 4), dtype=float)

c = np.dot(m1, v1)
c

array([142., 144., 169.])

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор. 

In [37]:
result_array = []
for _ in range(2):
    result_array.append([j for j in np.random.random(3)])
m1 = np.array(result_array, dtype=float)

v1 = np.array(np.random.random(3), dtype=float)

c = np.dot(m1, v1)
c

array([0.85143374, 0.67712915])

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [38]:
result_array = []
for _ in range(2):
    result_array.append([j for j in np.random.randint(1, 10, 2)])
m1 = np.array(result_array, dtype=int)    
    
result_array = []
for _ in range(2):
    result_array.append([j for j in np.random.randint(1, 10, 2)])
m2 = np.array(result_array, dtype=int)   

c = m1 * m2
c

array([[10, 24],
       [72, 10]])

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [39]:
result_array = []
for _ in range(2):
    result_array.append([j for j in np.random.randint(1, 10, 2)])
m1 = np.array(result_array, dtype=int)    
    
result_array = []
for _ in range(2):
    result_array.append([j for j in np.random.randint(1, 10, 2)])
m2 = np.array(result_array, dtype=int)   

c = np.dot(m1, m2)
c

array([[ 87,  35],
       [108,  72]])

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [41]:
result_array = []
for _ in range(5):
    result_array.append([j for j in np.random.randint(1, 100, 5)])
m1 = np.array(result_array, dtype=int)    

m1.sum()

1042

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [43]:
result_array = []
for _ in range(4):
    result_array.append([j for j in np.random.randint(1, 10, 4)])
m1 = np.array(result_array, dtype=int)    
    
result_array = []
for _ in range(4):
    result_array.append([j for j in np.random.randint(1, 10, 4)])
m2 = np.array(result_array, dtype=int)   

c = m1 - m2
c

array([[ 3, -5,  7,  0],
       [ 1,  6,  4, -1],
       [ 6, -6,  1,  0],
       [-1, -3,  3, -3]])

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [48]:
result_array = []
for _ in range(3):
    result_array.append([j for j in np.random.random(3)])
m1 = np.array(result_array, dtype=float)

print(m1)

c = np.array([np.sum(row) for row in m1])
c

[[0.22907728 0.95276649 0.03835184]
 [0.13362249 0.43825082 0.12419636]
 [0.45223309 0.34927199 0.38223188]]


array([1.22019561, 0.69606967, 1.18373697])

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [51]:
result_array = []
for _ in range(3):
    result_array.append([j for j in np.random.randint(1, 100, 4)])
m1 = np.array(result_array, dtype=int)    
print (m1)

m2 = m1 * m1
m2

[[86 71 76 70]
 [ 7 14 70 45]
 [49 51  7 39]]


array([[7396, 5041, 5776, 4900],
       [  49,  196, 4900, 2025],
       [2401, 2601,   49, 1521]])

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [59]:
v1 = np.array(np.random.randint(1, 50, 4), dtype=float)

print(v1)

v2 = np.array([x ** 0.5 for x in v1], dtype=float)
v2

[28. 34. 40. 21.]


array([5.29150262, 5.83095189, 6.32455532, 4.58257569])