In [14]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [15]:
a = np.array([i for i in range(1,11)], dtype=float)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [16]:
result_array = []
for _ in [0,0,0]:
    result_array.append([j for j in [0,0,0]])
    
a = np.array(result_array, dtype=float)
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [17]:
result_array = []
for _ in range(5):
    result_array.append(np.random.randint(1, 10, 5))
    
a = np.array(result_array, dtype=float)
a

array([[7., 7., 8., 8., 5.],
       [8., 7., 4., 3., 9.],
       [2., 3., 4., 9., 9.],
       [7., 4., 5., 8., 4.],
       [2., 4., 1., 5., 3.]])

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [18]:
result_array = []
for _ in range(4):
    result_array.append(np.random.random(4))
    
a = np.array(result_array, dtype=float)
a

array([[0.65747449, 0.36821015, 0.00320404, 0.52557623],
       [0.09601667, 0.93455856, 0.63924585, 0.75347186],
       [0.21059049, 0.61382081, 0.02459921, 0.67521198],
       [0.55455279, 0.4141005 , 0.12707749, 0.67168269]])

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [23]:
arr_1 = np.random.randint(1, 10, 5)
arr_2 = np.random.randint(1, 10, 5)

arr_1 + arr_2, arr_1 - arr_2, arr_1 * arr_2,  

(array([ 5, 13,  9,  5,  8]),
 array([-1, -5,  3,  3,  0]),
 array([ 6, 36, 18,  4, 16]))

6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [24]:
arr_1 = np.random.randint(1, 10, 5)
arr_2 = np.random.randint(1, 10, 5)

np.dot(arr_1, arr_2)

70